### ISSUE TITLE
panic after GET: interface conversion: interface {} is nil, not string [recovered]

### ISSUE THREAD

**Issue by aaronborden-rivian** [crossplane-contrib/provider-http#22]
I'm using Request to manage the lifecycle for the [registration of a GitLab Runner](https://docs.gitlab.com/runner/register/#register-with-a-runner-authentication-token) ([api](https://docs.gitlab.com/ee/api/users.html#create-a-runner-linked-to-a-user)).

The POST response payload returns a `token` which is used to register. The GET payload is different and does not include the token. The Warning is fair, that the token does not exist in the GET payload, but not sure where the panic is coming from.

In this use case, the Secret is created after the POST as expected. The Secret would never be updated as the token never expires or changes. When the runner is removed, that's when we want to de-register via DELETE.

### What happened?

provider-http pod crashes with panic.

```
{"level":"info","ts":"2024-05-16T16:22:19Z","logger":"provider-http","msg":"http request sent: {\"method\":\"GET\",\"url\":\"https://***/api/v4/runners/42160\",\"headers\":{\"Content-Type\":[\"application/json\"],\"PRIVATE-TOKEN\":[\"***\"]}}","request":"example-runner"}
{"level":"info","ts":"2024-05-16T16:22:19Z","logger":"provider-http","msg":"Warning, value at field .body.token is empty, skipping secret update for: &{{\"id\":42160,\"description\":\"example runner\",\"ip_address\":null,\"active\":true,\"paused\":false,\"is_shared\":false,\"runner_type\":\"group_type\",\"name\":null,\"online\":null,\"status\":\"never_contacted\",\"tag_list\":[\"example-tags\"],\"run_untagged\":true,\"locked\":false,\"maximum_timeout\":null,\"access_level\":\"not_protected\",\"version\":null,\"revision\":null,\"platform\":null,\"architecture\":null,\"contacted_at\":null,\"projects\":[],\"groups\":[{\"id\":96,\"web_url\":\"https://***/groups/vt/si-devops\",\"name\":\"SI DevOps\"}]} map[Cache-Control:[max-age=0, private, must-revalidate] Connection:[keep-alive] Content-Length:[510] Content-Type:[application/json] Date:[Thu, 16 May 2024 16:22:20 GMT] Etag:[W/\"57c4b135a3bc04f5f7338dc7e237cf8a\"] Referrer-Policy:[strict-origin-when-cross-origin] Set-Cookie:[glbsticky=1715876541.321.17457.213499|155a34ed77d2269bfc4c9d6f5ac87e98; Expires=Thu, 16-May-24 16:27:20 GMT; Max-Age=300; Path=/; Secure; HttpOnly] Strict-Transport-Security:[max-age=63072000] Vary:[Origin] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] X-Gitlab-Meta:[{\"correlation_id\":\"01HY13CBX29KRPP1QEKH3GKHXM\",\"version\":\"1\"}] X-Request-Id:[01HY13CBX29KRPP1QEKH3GKHXM] X-Runtime:[0.032985]] 200}","request":"example-runner"}
panic: interface conversion: interface {} is nil, not string [recovered]
        panic: interface conversion: interface {} is nil, not string

goroutine 143 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1a4
panic({0x11bb420, 0x40008596b0})
        runtime/panic.go:884 +0x1f4
github.com/crossplane-contrib/provider-http/internal/controller/request.(*external).desiredState(...)
        github.com/crossplane-contrib/provider-http/internal/controller/request/observe.go:99
github.com/crossplane-contrib/provider-http/internal/controller/request.(*external).isUpToDate(0x4000629a70, {0x1604208, 0x40006296e0}, 0x4000175400)
        github.com/crossplane-contrib/provider-http/internal/controller/request/observe.go:62 +0x60c
github.com/crossplane-contrib/provider-http/internal/controller/request.(*external).Observe(0x4000629a70, {0x1604208, 0x40006296e0}, {0x1617d88?, 0x4000175400})
        github.com/crossplane-contrib/provider-http/internal/controller/request/request.go:146 +0x60
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0x4000184840, {0x1604240, 0x4000629620}, {{{0x0, 0x0}, {0x40000c9728, 0x12}}})
        github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230413174155-c8cff1a7fb74/pkg/reconciler/managed/reconciler.go:805 +0x21f0
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0x40000888c0, {0x1604240, 0x4000629620}, {{{0x0?, 0x30?}, {0x40000c9728?, 0xffff69e06701?}}})
        github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230413174155-c8cff1a7fb74/pkg/ratelimiter/reconciler.go:54 +0x124
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1604240?, {0x1604240?, 0x4000629620?}, {{{0x0?, 0x112c420?}, {0x40000c9728?, 0x15f1fd0?}}})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x40004826e0, {0x1604198, 0x400007f810}, {0x1204e20?, 0x40004146c0?})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x2c0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x40004826e0, {0x1604198, 0x400007f810})
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1a0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x43c
```

### How can we reproduce it?

```
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-http
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-http:v1.0.0"
---
apiVersion: http.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: http-conf
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: example-runner
spec:
  forProvider:
    headers:
      PRIVATE-TOKEN:
        - "***"
      Content-Type:
        - application/json
    payload:
      baseUrl: "https://***/api/v4/"
      body: |-
        {
          "runner_type": "group_type",
          "group_id": 96,
          "description": "example runner",
          "tag_list": ["example-tags"]
          "paused": false,
          "run_untagged": false,
          "locked": false,
          "access_level": "not_protected",
          "maintenance_note": "",
        }
    mappings:
      - method: "POST"
        body: |
          {
            "runner_type": .payload.body.runner_type,
            "group_id": .payload.body.group_id,
            "description": .payload.body.description,
            "tag_list": .payload.body.tag_list,
            "run_untagged": .payload.body.run_untagged,
            "paused": .payload.body.paused,
            "locked": .payload.body.locked,
            "access_level": .payload.body.access_level
          }
        url: (.payload.baseUrl + "user/runners")
      - method: "GET"
        url: (.payload.baseUrl + "runners/" + (.response.body.id|tostring))
      - method: "DELETE"
        url: (.payload.baseUrl + "runners/" + (.response.body.id|tostring))
    secretInjectionConfigs:
      - secretRef:
          name: gitlab-runner-registration
          namespace: default
        secretKey: runner-token
        responsePath: .body.token
  providerConfigRef:
    name: http-conf
```

### What environment did it happen in?
Crossplane version: 1.15.3
provider-http: v1.0.0

rancher-desktop 1.13.1
kubernetes: 1.28.7

**Comment by arielsepton** [comment]
The problem lies in the absence of a PUT mapping. The provider uses the PUT mapping body to check if it is contained in the GET response. If it’s not, a PUT request is sent to update the resource.

Since your configuration lacks a PUT mapping, the provider can’t provision the resource and ensure it’s up to date. A good idea would be to cancel that operation when a PUT mapping is missing, but in the meantime, I recommend adding a PUT mapping with a body field that indicates the resource is up to date when it’s returned in each GET response (every reconcile).

If you need assistance with the implementation, please provide the structure of the GET response JSON, and I’ll be happy to help.

**Comment by aaronborden-rivian** [comment]
Thanks! Confirmed that specifying PUT avoid the panic. Here's the updated resource:
```
---
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: gitlab-runner
spec:
  forProvider:
    headers:
      PRIVATE-TOKEN:
        - "***"
      Content-Type:
        - application/json
    payload:
      baseUrl: "https://***/api/v4/"
      body: |-
        {
          "runner_type": "group_type",
          "group_id": 96,
          "description": "example runner",
          "tag_list": ["example-tags" ,"notagoodidea"],
          "paused": false,
          "run_untagged": false,
          "locked": false,
          "access_level": "not_protected",
          "maintenance_note": ""
        }

    mappings:
      - method: POST
        url: (.payload.baseUrl + "user/runners")
        body: |
          {
            "runner_type": .payload.body.runner_type,
            "group_id": .payload.body.group_id,
            "description": .payload.body.description,
            "tag_list": .payload.body.tag_list,
            "run_untagged": .payload.body.run_untagged,
            "paused": .payload.body.paused,
            "locked": .payload.body.locked,
            "access_level": .payload.body.access_level
          }
      - method: GET
        url: (.payload.baseUrl + "runners/" + (.response.body.id|tostring))
      - method: PUT
        url: (.payload.baseUrl + "runners/" + (.response.body.id|tostring))
        body: |
          {
            "runner_type": .payload.body.runner_type,
            "group_id": .payload.body.group_id,
            "description": .payload.body.description,
            "tag_list": .payload.body.tag_list,
            "run_untagged": .payload.body.run_untagged,
            "paused": .payload.body.paused,
            "locked": .payload.body.locked,
            "access_level": .payload.body.access_level
          }
      - method: DELETE
        url: (.payload.baseUrl + "runners/" + (.response.body.id|tostring))
    secretInjectionConfigs:
      - secretRef:
          name: gitlab-registration-http
          namespace: default
        secretKey: runner-token
        responsePath: .body.token
  providerConfigRef:
    name: http-conf
```

**Comment by jbw976** [comment]
>  A good idea would be to cancel that operation when a PUT mapping is missing

agreed @arielsepton, handling this more gracefully to avoid the entire provider crashing (which affects the reconciliation of other resources too) would be ideal. Perhaps this condition could be surfaced as an event and/or status condition on the object 🤓

**Comment by arielsepton** [comment]
@jbw976 I opted to handle this by skipping the action altogether when the PUT mapping is missing because, overall, the PUT doesn't exist, so there's no use in performing that check. Feel free to check out the PR for more insights!
